### PR TITLE
moved CONTRIBUTING.md file into the root directory  #134

### PR DESCRIPTION
**Pull request by peeplika**

### CODE REVIEW

**Comment by peeplika** [comment]
closes #134

**Comment by Remi-Gau** [comment]
I had put it there so that it would be rendered in the website.

If you want it in the root, you should remove it from the table of content of the website: 

https://github.com/INCF/artem-is/blob/631a75c12bfff69e8687f72027b0b9345c07dc3c/mkdocs.yml#L13

**Comment by peeplika** [comment]
Thanks for clarifying , I wasn't aware of that. Its better to keep CONTRIBUTING.md in ```src``` then. I think I should close the issue.

**Comment by Remi-Gau** [comment]
Or maybe at least add a link in the readme to point to the contributing.md document?

**Pull request closed without merging**
